spring actuator 추가
themoment-team/GSM-Networking-server pull request #38
Opened 2023-11-01 15:44 UTC by hajeu

## 개요

spring actuator 기능을 추가하였습니다.

## 본문

spring actuator를 사용하여서 Health Check를 구현하였습니다.

2023-11-01 23:07 UTC, YangSiJun528 requested changes
보안 상 외부에서 접근하지 못하게 다른 포트에서 실행되도록 하는게 좋습니다.

AWS 환경에서 private subnet 내부에서만 접근 가능하게 포트 설정 추가 부탁드려요.

2023-11-02 00:14 UTC, YangSiJun528 approved these changes
네 수고하셨어요. 환경변수 값 추가된 정보는 디코 env 방에 공유해주세요.

2023-11-03 13:27 UTC, SungGil-5125 commented on src/main/resources/application-prod.yml
> +    port: ${ACTUATOR_SERVER_PORT}
개인적으로 DB 같은 인프라 구성도 `health` 에 띄우면 어떨까 싶어요. cc @YangSiJun528 
다만 장애가 전파되지 않는 선으로 `health check` 가 가능하도록 구현하면 더 좋을거 같아요.

제가 읽고 좋았던 `spring actuator` 블로그 하나 첨부해드릴게요.
http://forward.nhnent.com/hands-on-labs/java.spring-boot-actuator/06-health.html

2023-11-03 13:36 UTC, YangSiJun528 commented on src/main/resources/application-prod.yml
> +    port: ${ACTUATOR_SERVER_PORT}
저도 동의합니다. 스프링 서버만 살아있고, DB가 죽거나 연결이 안된 상태면  사실 상 down 된 상태로 보는게 맞다고 생각해요.
아마 spring actuator 설정에 db connection 여부도 검사하는 옵션이 있는 걸로 압니다.

2023-11-04 07:23 UTC, hajeu commented on src/main/resources/application-prod.yml
> +    port: ${ACTUATOR_SERVER_PORT}
보내주신 자료들 읽어보고 찾아서 반영해보도록 하겠습니다!

2023-11-04 08:23 UTC, hajeu commented on src/main/resources/application-prod.yml
> +    port: ${ACTUATOR_SERVER_PORT}
반영해 보았습니다.
[fdefc20](https://github.com/themoment-team/GSM-Networking-server/pull/38/commits/fdefc20a4e3dbef428ec4c1a25ebd5125df0fc9f)
redis는 다운되었을때 다른 방식으로 대응이 가능 할것 같아서 장애가 전이 되지 않도록 설정했는데 선배님들의 생각이 궁금합니다
@SungGil-5125 @YangSiJun528

2023-11-04 09:12 UTC, YangSiJun528 commented on src/main/resources/application-prod.yml
> +    port: ${ACTUATOR_SERVER_PORT}
저도 redis가 다운되었을 때, 서버 기능 전부가 문제가 생기진 않는다고 생각합니다.
하지만 일부 기능(JWT 갱신, 본인인증 등)에서 문제가 발생됩니다. 
그렇다면 요청을 정상적으로 처리할 수 없는 down 상태라고 보아야 맞지 않을까요?


> redis는 다운되었을때 다른 방식으로 대응이 가능 할것 같아서 

무슨 대응 방식인지 설명해 주실 수 있나요?
지금 서버 상태에서 redis 연결이 끊어지더라도 서버에서 문제가 되는(JWT 갱신, 본인인증 등) 기능을 수행할 수 있는 대응 방법인가요?
그렇다 하더라도 지금처럼 대응 방안이 적용되지 않은 상태에서는 down으로 봐야하지 않을까 싶네요.

2023-11-04 09:19 UTC, hajeu commented on src/main/resources/application-prod.yml
> +    port: ${ACTUATOR_SERVER_PORT}
서버 기능 전부가 문제가 되지 않아서 빠르게 복구하면 되지 않을까 생각했었는데 제 생각이 짧았던것 같습니다.
down으로 보는게 맞을것 같습니다 수정하도록 하겠습니다

2023-11-04 09:38 UTC, YangSiJun528 commented on src/main/resources/application-prod.yml
> +    port: ${ACTUATOR_SERVER_PORT}
넵 알겠습니다. 

결국에 복구하는 동작을 위해선 "정상적인 상태인지 확인"하는 기능이 필요한데, 이러한 기능이 health check라고 생각합니다.

2023-11-04 12:45 UTC, SungGil-5125 commented on src/main/resources/application-prod.yml
> +    port: ${ACTUATOR_SERVER_PORT}
저도 시준이 의견에 동감합니다. 기존 redis 서버가 다운되면 어플리케이션이 정상적으로 동작하지 않을테니깐 거의 절반정도 down 된 상태로 보는게 맞다고 봐요.

2023-11-04 12:47 UTC, merged